import api from "./index";
import { ENDPOINTS } from "./endpoints";
export const createShiftType = async (data) => api.post(ENDPOINTS.SHIFT_TYPES.BASE, data);
export const getAllShiftTypes = async () => api.get(ENDPOINTS.SHIFT_TYPES.BASE);
export const getShiftTypeById = async (id) => api.get(ENDPOINTS.SHIFT_TYPES.BY_ID(id));
export const updateShiftType = async (id, data) => api.put(ENDPOINTS.SHIFT_TYPES.BY_ID(id), data);
export const deleteShiftType = async (id) => api.delete(ENDPOINTS.SHIFT_TYPES.BY_ID(id));
export const searchShiftTypes = async (data) => api.post(ENDPOINTS.SHIFT_TYPES.SEARCH, data);
export const createShiftLocation = async (data) => api.post(ENDPOINTS.SHIFT_LOCATIONS.BASE, data);
export const getAllShiftLocations = async () => api.get(ENDPOINTS.SHIFT_LOCATIONS.BASE);
export const getShiftLocationById = async (id) => api.get(ENDPOINTS.SHIFT_LOCATIONS.BY_ID(id));
export const updateShiftLocation = async (id, data) => api.put(ENDPOINTS.SHIFT_LOCATIONS.BY_ID(id), data);
export const deleteShiftLocation = async (id) => api.delete(ENDPOINTS.SHIFT_LOCATIONS.BY_ID(id));
export const searchShiftLocations = async (data) => api.post(ENDPOINTS.SHIFT_LOCATIONS.SEARCH, data);
export const createShiftAssignment = async (data) => api.post(ENDPOINTS.SHIFT_ASSIGNMENTS.BASE, data);
export const getAllShiftAssignments = async () => api.get(ENDPOINTS.SHIFT_ASSIGNMENTS.BASE);
export const getShiftAssignmentById = async (id) => api.get(ENDPOINTS.SHIFT_ASSIGNMENTS.BY_ID(id));
export const updateShiftAssignment = async (id, data) => api.put(ENDPOINTS.SHIFT_ASSIGNMENTS.BY_ID(id), data);
export const deleteShiftAssignment = async (id) => api.delete(ENDPOINTS.SHIFT_ASSIGNMENTS.BY_ID(id));
export const searchShiftAssignments = async (data) => api.post(ENDPOINTS.SHIFT_ASSIGNMENTS.SEARCH, data);
export const createShiftSchedule = async (data) => api.post(ENDPOINTS.SHIFT_SCHEDULES.BASE, data);
export const getAllShiftSchedules = async () => api.get(ENDPOINTS.SHIFT_SCHEDULES.BASE);
export const getShiftScheduleById = async (id) => api.get(ENDPOINTS.SHIFT_SCHEDULES.BY_ID(id));
export const updateShiftSchedule = async (id, data) => api.put(ENDPOINTS.SHIFT_SCHEDULES.BY_ID(id), data);
export const deleteShiftSchedule = async (id) => api.delete(ENDPOINTS.SHIFT_SCHEDULES.BY_ID(id));
export const searchShiftSchedules = async (data) => api.post(ENDPOINTS.SHIFT_SCHEDULES.SEARCH, data);
export const createShiftScheduleAssignment = async (data) => api.post(ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.BASE, data);
export const getAllShiftScheduleAssignments = async () => api.get(ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.BASE);
export const getShiftScheduleAssignmentById = async (id) => api.get(ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.BY_ID(id));
export const updateShiftScheduleAssignment = async (id, data) => api.put(ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.BY_ID(id), data);
export const deleteShiftScheduleAssignment = async (id) => api.delete(ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.BY_ID(id));
export const searchShiftScheduleAssignments = async (data) => api.post(ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.SEARCH, data);
export const createEmployeeCheckin = async (data) => api.post(ENDPOINTS.EMPLOYEE_CHECKINS.BASE, data);
export const getAllEmployeeCheckins = async () => api.get(ENDPOINTS.EMPLOYEE_CHECKINS.BASE);
export const getEmployeeCheckinById = async (id) => api.get(ENDPOINTS.EMPLOYEE_CHECKINS.BY_ID(id));
export const updateEmployeeCheckin = async (id, data) => api.put(ENDPOINTS.EMPLOYEE_CHECKINS.BY_ID(id), data);
export const deleteEmployeeCheckin = async (id) => api.delete(ENDPOINTS.EMPLOYEE_CHECKINS.BY_ID(id));
export const searchEmployeeCheckins = async (data) => api.post(ENDPOINTS.EMPLOYEE_CHECKINS.SEARCH, data);
export const generateShiftAssignments = async (id, data) => api.post(`${ENDPOINTS.SHIFT_SCHEDULE_ASSIGNMENTS.BY_ID(id)}/generate`, data);
