/**
 * Functional roles from the "Org Tier Page Access" proposal (claude.ai artifact
 * 5u5F2TonBJJMpizEHXAUj9): HR Head, HR Executive, Payroll, Recruiter, Hiring
 * Manager & Interviewer, Finance, L&D Coordinator, System Admin, Auditor.
 *
 * Generated from the artifact text — the action flags (w create, e edit /
 * approve / process, d delete) are read off each row's wording, so review them
 * before trusting a role with real data. Format: [menuUrl, actions, scope].
 * Scope words: assigned → all (the matrix cannot restrict to assigned
 * companies/branches/openings), config → no row scope (settings and master
 * data), ref → no row scope, own / direct / team / all as in org-tiers.data.js.
 *
 * KNOWN LIMITS (see org-tiers.data.js for the single-scope matrix limit):
 * - The proposal stacks a functional role ON TOP of a tier; an Employee holds
 *   exactly one role. Each functional role here therefore also carries the
 *   Employee tier's pages (own leave, own payslips…) — where a page is in both,
 *   the functional row wins outright, so an HR Executive can view everyone's
 *   leave but cannot apply for their own through the matrix.
 * - ASSIGNED company/branch scoping, maker–checker (two different people),
 *   "never on your own record", expiring grants and masked fields are not
 *   enforced by a permission row; they need code.
 */
export const FUNCTIONAL_ROLES = {
  "HR Head": {
    links: [["/dashboard","assigned"],["/documentation","ref"]],
    pages: [
      ["/user-roles","e","config"],
      ["/company","we","config"],
      ["/branch","we","config"],
      ["/department","we","config"],
      ["/designation","we","config"],
      ["/employment-type","we","config"],
      ["/employee-grade","we","config"],
      ["/employee","we","assigned"],
      ["/employee-health-insurance","wed","assigned"],
      ["/job-requisition","e","assigned"],
      ["/job-opening","","assigned"],
      ["/job-applicant","","assigned"],
      ["/job-applicant-source","wed","config"],
      ["/interview-type","wed","config"],
      ["/interview","","assigned"],
      ["/interview-feedback","","assigned"],
      ["/job-offer","we","assigned"],
      ["/job-offer-term-template","we","config"],
      ["/employee-separation","e","assigned"],
      ["/employee-onboarding","e","assigned"],
      ["/employee-onboarding-template","we","config"],
      ["/employee-separation-template","we","config"],
      ["/exit-interview","","assigned"],
      ["/full-and-final-statement","e","assigned"],
      ["/employee-grievance","e","assigned"],
      ["/employee-referral","e","assigned"],
      ["/grievance-type","wed","config"],
      ["/employee-transfer","e","assigned"],
      ["/employee-promotion","e","assigned"],
      ["/staffing-plan","we","assigned"],
      ["/training-program","","assigned"],
      ["/training-event","","assigned"],
      ["/travel-request","e","assigned"],
      ["/purpose-of-travel","wed","config"],
      ["/identification-document-type","wed","config"],
      ["/leave-allocation","","assigned"],
      ["/compensatory-leave-request","","assigned"],
      ["/leave-application","e","assigned"],
      ["/holiday-list","e","config"],
      ["/leave-type","we","config"],
      ["/leave-period","we","config"],
      ["/leave-policy","we","config"],
      ["/leave-policy-assignment","","assigned"],
      ["/leave-ledger-entry","","assigned"],
      ["/leave-adjustment","e","assigned"],
      ["/leave-encashment","e","assigned"],
      ["/leave-block-list","w","config"],
      ["/shift-assignment","","assigned"],
      ["/employee-checkin","","assigned"],
      ["/attendance","","assigned"],
      ["/shift-type","we","config"],
      ["/salary-slip","","assigned"],
      ["/salary-component","","config"],
      ["/salary-structure","","config"],
      ["/salary-structure-assignment","e","assigned"],
      ["/bulk-salary-structure-assignment","we","assigned"],
      ["/payroll-entry","we","assigned"],
      ["/retention-bonus","e","assigned"],
      ["/employee-incentive","e","assigned"],
      ["/payroll-correction","e","assigned"],
      ["/gratuity","e","assigned"],
      ["/appraisal","we","assigned"],
      ["/goal","","assigned"],
      ["/employee-performance-feedback","","assigned"],
      ["/kra","we","config"],
      ["/employee-feedback-criteria","we","config"],
      ["/appraisal-template","we","config"],
      ["/appraisal-cycle","we","config"],
      ["/expense-claim","","assigned"],
      ["/expense-claim-type","w","config"],
      ["/login-attempt-logs","","assigned"],
      ["/audit-log","","assigned"],
      ["/email-template","e","config"],
    ],
  },
  "HR Executive": {
    links: [["/dashboard","assigned"],["/documentation","ref"]],
    pages: [
      ["/company","","config"],
      ["/branch","","config"],
      ["/department","","config"],
      ["/designation","","config"],
      ["/employment-type","","config"],
      ["/employee-grade","","config"],
      ["/employee","we","assigned"],
      ["/employee-health-insurance","we","assigned"],
      ["/employee-separation","e","assigned"],
      ["/employee-onboarding","w","assigned"],
      ["/employee-onboarding-template","","config"],
      ["/employee-separation-template","","config"],
      ["/exit-interview","w","assigned"],
      ["/full-and-final-statement","e","assigned"],
      ["/employee-grievance","e","assigned"],
      ["/employee-referral","e","assigned"],
      ["/employee-transfer","we","assigned"],
      ["/employee-promotion","we","assigned"],
      ["/staffing-plan","","assigned"],
      ["/travel-request","we","assigned"],
      ["/purpose-of-travel","","config"],
      ["/identification-document-type","","config"],
      ["/leave-allocation","we","assigned"],
      ["/compensatory-leave-request","","assigned"],
      ["/leave-application","","assigned"],
      ["/holiday-list","we","config"],
      ["/leave-type","","config"],
      ["/leave-period","","config"],
      ["/holiday-list-assignment","e","assigned"],
      ["/leave-policy","","config"],
      ["/leave-policy-assignment","e","assigned"],
      ["/leave-ledger-entry","","assigned"],
      ["/leave-adjustment","we","assigned"],
      ["/leave-encashment","w","assigned"],
      ["/leave-block-list","","config"],
      ["/leave-control-panel","w","assigned"],
      ["/shift-assignment","we","assigned"],
      ["/employee-checkin","e","assigned"],
      ["/attendance","","assigned"],
      ["/shift-request","","assigned"],
      ["/attendance-request","","assigned"],
      ["/shift-type","","config"],
      ["/shift-location","we","config"],
      ["/shift-schedule","we","config"],
      ["/shift-schedule-assignment","e","assigned"],
      ["/shift-assignment-tool","we","assigned"],
      ["/employee-attendance-tool","we","assigned"],
      ["/appraisal","","assigned"],
      ["/goal","","assigned"],
      ["/email-template","","config"],
    ],
  },
  "Payroll": {
    links: [["/dashboard","assigned"],["/documentation","ref"]],
    pages: [
      ["/employee","","assigned"],
      ["/employee-health-insurance","","assigned"],
      ["/full-and-final-statement","we","assigned"],
      ["/employee-promotion","we","assigned"],
      ["/leave-allocation","","assigned"],
      ["/leave-application","e","assigned"],
      ["/leave-ledger-entry","","assigned"],
      ["/leave-encashment","we","assigned"],
      ["/attendance","","assigned"],
      ["/salary-slip","we","assigned"],
      ["/employee-other-income","e","assigned"],
      ["/employee-benefit-application","e","assigned"],
      ["/employee-benefit-claim","e","assigned"],
      ["/employee-benefit-ledger","","assigned"],
      ["/employee-tax-exemption-declaration","we","assigned"],
      ["/employee-tax-exemption-proof-submission","e","assigned"],
      ["/salary-component","we","config"],
      ["/salary-structure","we","config"],
      ["/salary-structure-assignment","we","assigned"],
      ["/bulk-salary-structure-assignment","we","assigned"],
      ["/payroll-period","w","config"],
      ["/payroll-settings","e","config"],
      ["/payroll-entry","we","assigned"],
      ["/salary-withholding","we","assigned"],
      ["/additional-salary","w","assigned"],
      ["/arrear","we","assigned"],
      ["/retention-bonus","we","assigned"],
      ["/employee-incentive","we","assigned"],
      ["/payroll-correction","we","assigned"],
      ["/income-tax-slab","we","config"],
      ["/employee-tax-exemption-category","we","config"],
      ["/employee-tax-exemption-sub-category","we","config"],
      ["/gratuity-rule","we","config"],
      ["/gratuity","we","assigned"],
    ],
  },
  "Recruiter": {
    links: [["/dashboard","assigned"]],
    pages: [
      ["/job-requisition","","assigned"],
      ["/job-opening","we","assigned"],
      ["/job-applicant","we","assigned"],
      ["/job-applicant-source","","config"],
      ["/interview-type","","config"],
      ["/interview","we","assigned"],
      ["/interview-feedback","","assigned"],
      ["/job-offer","we","assigned"],
      ["/job-offer-term-template","","config"],
      ["/employee-onboarding","w","assigned"],
      ["/employee-referral","e","assigned"],
      ["/staffing-plan","","assigned"],
      ["/email-template","","config"],
    ],
  },
  "Hiring Manager & Interviewer": {
    links: [],
    pages: [
      ["/job-requisition","w","assigned"],
      ["/job-opening","e","assigned"],
      ["/job-applicant","","assigned"],
      ["/interview","e","assigned"],
      ["/interview-feedback","we","assigned"],
      ["/job-offer","","assigned"],
      ["/employee-onboarding","e","assigned"],
    ],
  },
  "Finance": {
    links: [["/dashboard","assigned"]],
    pages: [
      ["/full-and-final-statement","we","assigned"],
      ["/travel-request","w","assigned"],
      ["/salary-slip","e","assigned"],
      ["/employee-benefit-claim","e","assigned"],
      ["/payroll-entry","we","assigned"],
      ["/gratuity","we","assigned"],
      ["/expense-claim","we","assigned"],
      ["/expense-claim-type","w","config"],
    ],
  },
  "L&D Coordinator": {
    links: [["/dashboard","assigned"]],
    pages: [
      ["/training-feedback","","assigned"],
      ["/training-program","we","assigned"],
      ["/training-event","we","assigned"],
      ["/skill","we","config"],
      ["/employee-skill-map","e","assigned"],
    ],
  },
  "System Admin": {
    links: [["/dashboard","config"],["/documentation","ref"]],
    pages: [
      ["/admin-user","we","config"],
      ["/user-roles","e","config"],
      ["/dashboard-builder","we","config"],
      ["/country","we","config"],
      ["/state","we","config"],
      ["/city","we","config"],
      ["/currency-master","we","config"],
      ["/role-master","we","config"],
      ["/menu-group","we","config"],
      ["/menu-master","we","config"],
      ["/login-attempt-logs","","config"],
      ["/audit-log","","config"],
      ["/email-setup","we","config"],
      ["/email-for","we","config"],
      ["/email-template","e","config"],
    ],
  },
  "Auditor": {
    links: [],
    pages: [
      ["/user-roles","","config"],
      ["/employee","","assigned"],
      ["/full-and-final-statement","","assigned"],
      ["/leave-ledger-entry","","assigned"],
      ["/attendance","","assigned"],
      ["/salary-slip","","assigned"],
      ["/salary-structure-assignment","","assigned"],
      ["/payroll-entry","","assigned"],
      ["/additional-salary","","assigned"],
      ["/arrear","","assigned"],
      ["/employee-incentive","","assigned"],
      ["/payroll-correction","","assigned"],
      ["/gratuity","","assigned"],
      ["/expense-claim","","assigned"],
      ["/login-attempt-logs","","assigned"],
      ["/audit-log","","assigned"],
    ],
  },
};
