import PayrollEntry from "../pages/Payroll/PayrollEntry";
import { Navigate } from "react-router-dom";
import { crudRoutes } from "@/components/crud";
import { UNIFORM_ENTITIES } from "@/entities";
import { ADVANCED_ENTITIES, payrollEntryConfig } from "@/entities/advanced";

import Login from "../pages/Authentication/Login";
import UserProfile from "../pages/Authentication/user-profile";
import Dashboard from "../pages/Dashboard/Dashboard";
import UserRoles from "../pages/Setup/UserRoles";
import DashboardBuilder from "../pages/Setup/DashboardBuilder";
import DashboardSectionEditor from "../pages/Setup/DashboardSectionEditor";
import LoginAttemptLogs from "../pages/Master/LoginAttemptLogs";
import AuditLog from "../pages/Master/AuditLog";
import LeaveLedgerEntries from "../pages/Leaves/LeaveLedgerEntries";
import LeaveControlPanel from "../pages/Leaves/LeaveControlPanel";
import ShiftAssignmentTool from "../pages/ShiftAttendance/ShiftAssignmentTool";
import EmployeeAttendanceTool from "../pages/ShiftAttendance/EmployeeAttendanceTool";
import BulkSalaryStructureAssignmentTool from "../pages/Payroll/BulkSalaryStructureAssignmentTool";
import PayrollSettings from "../pages/Payroll/PayrollSettings";
import Documentation from "../pages/Documentation";

const authProtectedRoutes = [
    { path: "/dashboard", component: <Dashboard /> },
    { path: "/profile", component: <UserProfile /> },

    // list / add / view / edit for every CRUD entity
    ...[...UNIFORM_ENTITIES, ...ADVANCED_ENTITIES].flatMap(crudRoutes),

    // Not CRUD screens: a permission matrix, a read-only audit log, a settings
    // singleton.
    { path: "/user-roles", component: <UserRoles /> },
    // Dashboard Builder is the library + the dashboard assignment; building one
    // section is its own screen — the live preview beside the inputs needs
    // the room.
    { path: "/dashboard-builder", component: <DashboardBuilder /> },
    { path: "/dashboard-builder/add", component: <DashboardSectionEditor key="dashboard-section-add" mode="add" /> },
    { path: "/dashboard-builder/edit/:id", component: <DashboardSectionEditor key="dashboard-section-edit" mode="edit" /> },
    { path: "/login-attempt-logs", component: <LoginAttemptLogs /> },
    { path: "/audit-log", component: <AuditLog /> },
    // ADR-027 (Payroll — Run, foundation half): a true global singleton,
    // genuinely not a CRUD screen.
    crudRoutes(payrollEntryConfig)[0],
    { path: "/payroll-entry/add", component: <PayrollEntry /> },
    { path: "/payroll-entry/:id", component: <PayrollEntry /> },
    { path: "/payroll-entry/:id/edit", component: <PayrollEntry /> },
    { path: "/payroll-settings", component: <PayrollSettings /> },
    // ADR-024: LeaveLedgerEntry is append-only/system-written, no create/
    // update/delete endpoint at all — same reasoning as AuditLog above.
    { path: "/leave-ledger-entry", component: <LeaveLedgerEntries /> },
    // ADR-024 (module complete): stateless bulk-action form, no stored model
    // — same reasoning as LeaveLedgerEntries above.
    { path: "/leave-control-panel", component: <LeaveControlPanel /> },
    // ADR-025 (module complete): stateless bulk-action forms, no stored
    // model — same reasoning as LeaveControlPanel above.
    { path: "/shift-assignment-tool", component: <ShiftAssignmentTool /> },
    { path: "/employee-attendance-tool", component: <EmployeeAttendanceTool /> },
    // ADR-026: stateless bulk-action form, no stored model — same reasoning
    // as ShiftAssignmentTool/LeaveControlPanel above.
    { path: "/bulk-salary-structure-assignment", component: <BulkSalaryStructureAssignmentTool /> },

    // End-user documentation (ADR-011). The markdown is generated by
    // `npm run docs` and bundled at build time, so these are plain routes with
    // no data loading of their own.
    { path: "/documentation", component: <Documentation /> },
    { path: "/documentation/:pageKey", component: <Documentation /> },

    { path: "/", exact: true, component: <Navigate to="/dashboard" /> },
    { path: "*", component: <Navigate to="/dashboard" /> },
];

const publicRoutes = [{ path: "/", component: <Login /> }];

export { authProtectedRoutes, publicRoutes };
